# Generated by Django 4.2.7 on 2023-11-21 21:48

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_blog_posted'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='posted',
            field=models.DateTimeField(db_index=True, default=datetime.datetime(2023, 11, 22, 0, 48, 0, 767035), verbose_name='Опубликована'),
        ),
    ]
