# Generated by Django 4.2.7 on 2023-11-21 21:53

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_blog_author_alter_blog_posted'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='posted',
            field=models.DateTimeField(db_index=True, default=datetime.datetime(2023, 11, 22, 0, 53, 29, 762556), verbose_name='Опубликована'),
        ),
    ]
